### ISSUE TITLE
_AsyncTask.__await__ implementation question

### ISSUE THREAD

**Issue by eskuat** [nicoddemus/qt-async-threads#38]
Hi!

This is a question, not an issue.

I was playing with `_AsyncTask` and I have a question, why it yields self, what does it mean, how its supposed to be interpreted ? Python doc is very broad about what __await__ should do, so its not 100% clear whats happening here.

```

    def __await__(self) -> Generator[Any, None, None]:
        if any(x for x in self.futures if x.done()):
            return None
        else:
            yield self
``` 

For example this script throws an exception on `yield self` line

```
from __future__ import annotations
import asyncio
import threading
import time
from collections.abc import Awaitable
from collections.abc import Coroutine
from concurrent.futures import Future
from concurrent.futures import ThreadPoolExecutor
from typing import Any
from typing import Generator

import attr


@attr.s(auto_attribs=True, eq=False)
class _AsyncTask(Awaitable[None]):

    futures: set[Future]
    coroutine: Coroutine | None = None
    _lock: threading.Lock = attr.Factory(threading.Lock)

    def __await__(self) -> Generator[Any, None, None]:
        if any(x for x in self.futures if x.done()):
            return None
        else:
            yield self


def sleep(delay):
    time.sleep(delay)
    return delay


async def main():
    with ThreadPoolExecutor() as tpe:
        futures = [tpe.submit(sleep, delay) for delay in (2, 3)]
        t = _AsyncTask(set(futures))
        res = await t
    print("Done", res)

asyncio.run(main())

```

**Comment by nicoddemus** [comment]
What `__await__` returns really depend on the framework which is handling the async functions... in `qt-async-threads`, the handler expects the `_AsyncTest` to return itself if its futures are still running:

https://github.com/nicoddemus/qt-async-threads/blob/b310dd9266aa5bf3a5eb8b9193da57436959ab90/src/qt_async_threads/_qt_async_runner.py#L172-L183

Unfortunately I Don't know enough about `asyncio` internals to know how implement your own awaitables.
